### ISSUE TITLE
Issues loading IRIS in director - cannot load any more module with static TLS

### ISSUE THREAD

**Issue by stoutheo06** [rdeits/iris-distro#50]
**System:** Ubuntu 14.04 Trusty, oh-distro-private installed (i7. 16GB)

Director crashes upon start with:

```
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/home/theo/software/oh-distro-private/software/build/lib/python2.7/dist-packages/director/startup.py", line 7, in <module>
    from director import irisdriver
  File "/home/theo/software/oh-distro-private/software/build/lib/python2.7/dist-packages/director/irisdriver.py", line 5, in <module>
    from director import irisUtils
  File "/home/theo/software/oh-distro-private/software/build/lib/python2.7/dist-packages/director/irisUtils.py", line 3, in <module>
    from irispy.utils import lcon_to_vert
  File "/home/theo/software/oh-distro-private/software/build/lib/python2.7/dist-packages/irispy/__init__.py", line 1, in <module>
    from irispy import inflate_region, Polyhedron, Ellipsoid, IRISRegion, IRISOptions, IRISProblem
  File "/home/theo/software/oh-distro-private/software/build/lib/python2.7/dist-packages/irispy/irispy.py", line 1, in <module>
    from iris_wrapper import IRISOptions, IRISRegion, IRISProblem, IRISDebugData, Ellipsoid, Polyhedron
  File "/home/theo/software/oh-distro-private/software/build/lib/python2.7/dist-packages/irispy/iris_wrapper.py", line 28, in <module>
    _iris_wrapper = swig_import_helper()
  File "/home/theo/software/oh-distro-private/software/build/lib/python2.7/dist-packages/irispy/iris_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_iris_wrapper', fp, pathname, description)
ImportError: dlopen: cannot load any more object with static TLS
```

@wxmerkt recommended LD_PRELOADing _iris_wrapper.so and this solves the problem locally.

**Comment by rdeits** [comment]
We have seen this before with Director on linux: https://github.com/RobotLocomotion/director/pull/152

Really, I think the best thing to do might just be *not* to import IRIS from director. I don't believe it's providing any functionality that's currently in use anywhere.

**Comment by wxmerkt** [comment]
Suggested fix by Pat in https://github.com/openhumanoids/oh-distro-private/issues/2609

``
LD_PRELOAD=$DRC_BASE/software/build/lib/libiomp5.so
``

**Comment by rdeits** [comment]
I be this is fixed in IRIS master. Interested in trying to update and fix it?

**Comment by wxmerkt** [comment]
Happy to close this issue
